assign_issues:
  - Yuan325
  - duwenxin99
  - averikitsch
assign_issues_by:
  - labels:
    - 'product: bigquery'
    to:
    - Genesis929
    - shobsi
    - jiaxunwu
  - labels:
    - 'product: looker'
    to:
    - drstrangelooker
assign_prs:
  - Yuan325
  - duwenxin99
  - averikitsch
